.PHONY: clean All

All:
	@echo "----------Building project:[ one - Debug ]----------"
	@cd "one" && "$(MAKE)" -f  "one.mk"
clean:
	@echo "----------Cleaning project:[ one - Debug ]----------"
	@cd "one" && "$(MAKE)" -f  "one.mk" clean
